config_version = 2

[bar.default]
border = "primary"
border_width = 0.5
center = [ "audio_visualizer_l", "clock", "media" ]
end = [
    "tray",
    "bluetooth",
    "volume",
    "notifications",
    "session"
]
margin_ends = 0
radius = 20
radius_top_left = 0
radius_top_right = 0
shadow = true
start = [ "launcher", "wallpaper", "workspaces", "date", "taskbar" ]
thickness = 35

[calendar]
enabled = true

[[control_center.shortcuts]]
type = "bluetooth"

[[control_center.shortcuts]]
type = "caffeine"

[[control_center.shortcuts]]
type = "notification"

[[control_center.shortcuts]]
type = "audio"

[[control_center.shortcuts]]
type = "session"

[[control_center.shortcuts]]
type = "system"

[desktop_widgets]
schema_version = 1
widget_order = [
    "desktop-widget-0000000000000006",
    "desktop-widget-0000000000000007",
    "desktop-widget-0000000000000005",
    "desktop-widget-0000000000000008",
    "desktop-widget-0000000000000009",
    "desktop-widget-000000000000000a",
    "desktop-widget-000000000000000b",
    "desktop-widget-000000000000000c"
]

    [desktop_widgets.grid]
    cell_size = 16
    major_interval = 4
    visible = true

    [desktop_widgets.widget.desktop-widget-0000000000000005]
    box_height = 0.0
    box_width = 0.0
    cx = 112.0
    cy = 144.0
    output = "DP-5"
    rotation = 0.0
    type = "sysmon"

        [desktop_widgets.widget.desktop-widget-0000000000000005.settings]
        color2 = "on_secondary"
        stat2 = "cpu_temp"

    [desktop_widgets.widget.desktop-widget-0000000000000006]
    box_height = 0.0
    box_width = 0.0
    cx = 112.0
    cy = 304.5
    output = "DP-5"
    rotation = 0.0
    type = "sysmon"

        [desktop_widgets.widget.desktop-widget-0000000000000006.settings]
        color2 = "on_secondary"
        stat = "gpu_usage"
        stat2 = "gpu_temp"

    [desktop_widgets.widget.desktop-widget-0000000000000007]
    box_height = 0.0
    box_width = 0.0
    cx = 316.0
    cy = 144.0
    output = "DP-5"
    rotation = 0.0
    type = "sysmon"

        [desktop_widgets.widget.desktop-widget-0000000000000007.settings]
        stat = "ram_pct"

[hooks]
started = "noctalia msg session lock"

[location]
auto_locate = true

[lockscreen]
monitors = [ "DP-2" ]

[lockscreen_widgets]
enabled = true
schema_version = 2
widget_order = [
    "lockscreen-login-box@DP-2",
    "lockscreen-login-box@WAYLAND-1",
    "lockscreen-login-box@DP-1",
    "lockscreen-login-box@DP-5",
    "lockscreen-login-box@DP-3",
]

[osd.kinds]
lock_keys = false

[notification]
history_retention_hours = 1

[plugins]
enabled = [ "noctalia/translator", "icefish/phone-connect" ]

    [[plugins.source]]
    kind = "git"
    location = "https://github.com/noctalia-dev/official-plugins"
    name = "official"

    [[plugins.source]]
    kind = "git"
    location = "https://github.com/noctalia-dev/community-plugins"
    name = "community"

    [[plugins.source]]
    kind = "path"
    location = "~/Projects"
    name = "my-plugins"

[shell]
external_ip_enabled = true
font_family = "JetBrainsMono Nerd Font"
polkit_agent = true
settings_show_advanced = true
telemetry_enabled = false

    [shell.panel]
    clipboard_placement = "floating"
    control_center_placement = "floating"
    open_near_click_control_center = true
    shadow = false
    transparency_mode = "glass"

    [shell.screenshot]
    copy_to_clipboard = true
    directory = "/home/maxfh/Pictures/screenshots"

[system.monitor]
cpu_poll_seconds = 1

[theme]
builtin = "Ayu"
community_palette = "Mine"
mode = "dark"
source = "wallpaper"
wallpaper_scheme = "m3-rainbow"

    [theme.templates]
    builtin_ids = [ "btop", "gtk3", "gtk4", "hyprland", "kitty", "niri", "qt" ]
    community_ids = [ "spicetify", "zen-browser", "lazygit", "opencode", "steam", "yazi" ]

[wallpaper]
directory = "/home/maxfh/Pictures/wallpapers"

    [wallpaper.default]
    path = "/home/maxfh/Pictures/wallpapers/sweet_btw.png"

    [wallpaper.last]
    path = "/home/maxfh/Pictures/wallpapers/sweet_btw.png"

    [wallpaper.monitors.DP-1]
    path = "/home/maxfh/Pictures/wallpapers/sweet_btw.png"

    [wallpaper.monitors.DP-3]
    path = "/home/maxfh/Pictures/wallpapers/sweet_btw.png"

    [wallpaper.monitors.DP-5]
    path = "/home/maxfh/Pictures/wallpapers/elden_ring.jpg"

[weather]
unit = "imperial"

[widget.audio_visualizer]
bands = 64
centered = false
color_2 = "secondary"
mirrored = false
width = 150.0

[widget.audio_visualizer_l]
bands = 64
centered = false
mirrored = false
type = "audio_visualizer"
width = 135.0

[widget.clock]
format = "{:%I:%M}"

[widget.date]
format = "{:%a %b %d}"

[widget.media]
hide_when_no_media = true
max_length = 135
title_scroll = "on_hover"

[widget.taskbar]
group_by_workspace = true
group_single_icon_per_app = true
show_all_outputs = true
workspace_label_placement = "centered"
